### ISSUE TITLE
I want to implement that a `scene` loads multiple `models`

### ISSUE THREAD

**Issue by jiawenquan** [saaratrix/generic-3Dproduct-viewer#8]
I want to implement that a `scene` loads multiple `models`, so I thought of modifying `ProductItem`  `filename: string;`  Change to `filenames: string[];`, so `LoadingProgressEventData` need to add a new id to determine if it is a model of the same `scene`, I don't know if this is thoughtful.

**Comment by haestflod** [comment]
If you want to load multiple model files quite a few things would need to be changed to load an array instead of just 1 item. filenames is one of them, `object3D?: Object3D;  should be an array unless you create a dummy object as parent. 

Creating a dummy root object is a good idea I think. 

The  loading as you mentioned needs to be different too.
